[package]
name = "bitcode_packing"
version.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
divan = "0.1.17"

[lints]
workspace = true
